name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get_it: ^8.0.3
  http: ^1.4.0
  hugeicons: ^0.0.11
  lottie: ^3.3.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

